name: 'TEST'
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Changelog
        id: github_release
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: "0.1.27"
          path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          always-auth: true
      - run: |
          echo "Body: ${{ steps.github_release.outputs.changes }}"
      - run: |
          echo "Body: ${{ steps.github_release.outputs.version }}"
      - run: |
          echo "Body: ${{ steps.github_release.outputs.date }}"
      - run: |
          echo "Body: ${{ steps.github_release.outputs.status }}"
      - name: Split Action
        id: split
        uses: rishabhgupta/split-by@v1
        with:
        # String to split
          string: '0.1.23' 
        # The delimiter to split the string
          split-by: '-'
      - name: Determine Checkout Depth
        uses: haya14busa/action-cond@v1
        id: tag
        with:
          cond: ${{ steps.split.outputs._1 == '' }}
          if_true: 'latest'  # string value
          if_false: ${{ steps.split.outputs._1 }}
      - run: |
          echo "Version: ${{ steps.tag.outputs.value }}"
      - uses: dangoslen/changelog-enforcer@v2
          
          
