name: 'TEST'
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: "1.0.0"
          path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "Body: ${{ steps.github_release.outputs.changelog }}"
