name: 'TEST'
on:
  pull_request:

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          always-auth: true
      - run: |
          echo "Body: ${{ steps.github_release.outputs.changelog }}"
